// <auto-generated />
using System;
using DataDep.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataDep.Migrations
{
    [DbContext(typeof(OurDbContext))]
    partial class OurDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataDep.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "D1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "D2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "D3"
                        });
                });

            modelBuilder.Entity("DataDep.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ChiefId")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChiefId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChiefId = 5,
                            DepartmentId = 1,
                            Name = "John",
                            Salary = 100
                        },
                        new
                        {
                            Id = 2,
                            ChiefId = 5,
                            DepartmentId = 1,
                            Name = "Misha",
                            Salary = 600
                        },
                        new
                        {
                            Id = 3,
                            ChiefId = 6,
                            DepartmentId = 2,
                            Name = "Eugen",
                            Salary = 300
                        },
                        new
                        {
                            Id = 4,
                            ChiefId = 6,
                            DepartmentId = 2,
                            Name = "Tolya",
                            Salary = 400
                        },
                        new
                        {
                            Id = 5,
                            ChiefId = 7,
                            DepartmentId = 3,
                            Name = "Stepan",
                            Salary = 500
                        },
                        new
                        {
                            Id = 6,
                            ChiefId = 7,
                            DepartmentId = 3,
                            Name = "Alex",
                            Salary = 1000
                        },
                        new
                        {
                            Id = 7,
                            DepartmentId = 3,
                            Name = "Ivan",
                            Salary = 1100
                        });
                });

            modelBuilder.Entity("DataDep.Employee", b =>
                {
                    b.HasOne("DataDep.Employee", "Chief")
                        .WithMany("Subordinates")
                        .HasForeignKey("ChiefId");

                    b.HasOne("DataDep.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chief");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("DataDep.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("DataDep.Employee", b =>
                {
                    b.Navigation("Subordinates");
                });
#pragma warning restore 612, 618
        }
    }
}
